---
- name: Debug LLDP Issues
  hosts: all
  become: yes

  tasks:
    - name: Check if lldpd is installed
      command: which lldpd
      register: lldpd_path
      failed_when: false
      changed_when: false

    - name: Check lldpd daemon arguments (Debian/Ubuntu)
      command: cat /etc/default/lldpd
      register: debian_config
      when: ansible_os_family == "Debian"
      failed_when: false
      changed_when: false

    - name: Check lldpd daemon arguments (RedHat/CentOS)
      command: cat /etc/sysconfig/lldpd
      register: redhat_config
      when: ansible_os_family == "RedHat"
      failed_when: false
      changed_when: false

    - name: Display Debian config
      debug:
        var: debian_config.stdout_lines
      when: ansible_os_family == "Debian" and debian_config.rc == 0

    - name: Display RedHat config
      debug:
        var: redhat_config.stdout_lines
      when: ansible_os_family == "RedHat" and redhat_config.rc == 0

    - name: Check lldpd logs
      command: journalctl -u lldpd -n 20 --no-pager
      register: lldpd_logs
      changed_when: false
      failed_when: false

    - name: Display lldpd logs
      debug:
        var: lldpd_logs.stdout_lines

    - name: Check if lldpd group exists
      command: getent group lldpd
      register: lldpd_group
      failed_when: false
      changed_when: false

    - name: Display group status
      debug:
        msg: "lldpd group {{ 'exists' if lldpd_group.rc == 0 else 'does not exist' }}"

    - name: Test lldpd with verbose output
      command: /usr/sbin/lldpd -d -g lldpd
      register: lldpd_test
      failed_when: false
      changed_when: false
      timeout: 5

    - name: Display test output
      debug:
        var: lldpd_test
