---
- name: Deploy and Configure LLDP on Linux Servers
  hosts: all
  become: yes
  
  vars:
    lldp_package: lldpd
    lldp_service: lldpd
    lldp_socket_group: lldpd
    
  tasks:
    - name: Install LLDP daemon on Debian/Ubuntu
      apt:
        name: "{{ lldp_package }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      
    - name: Install LLDP daemon on RedHat/CentOS
      yum:
        name: "{{ lldp_package }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Create lldpd group for socket access
      group:
        name: "{{ lldp_socket_group }}"
        state: present
        system: yes

    - name: Add current user to lldpd group
      user:
        name: "{{ ansible_user }}"
        groups: "{{ lldp_socket_group }}"
        append: yes
      when: ansible_user is defined and ansible_user != 'root'

    - name: Configure lldpd socket permissions (Debian/Ubuntu)
      lineinfile:
        path: /etc/default/lldpd
        regexp: '^DAEMON_ARGS='
        line: 'DAEMON_ARGS="-g {{ lldp_socket_group }}"'
        create: yes
        mode: '0644'
      when: ansible_os_family == "Debian"
      notify: restart lldpd

    - name: Configure lldpd socket permissions (RedHat/CentOS)
      lineinfile:
        path: /etc/sysconfig/lldpd
        regexp: '^LLDPD_OPTIONS='
        line: 'LLDPD_OPTIONS="-g {{ lldp_socket_group }}"'
        create: yes
        mode: '0644'
      when: ansible_os_family == "RedHat"
      notify: restart lldpd

    - name: Flush handlers to apply configuration changes
      meta: flush_handlers

    - name: Ensure LLDP service is enabled and started
      systemd:
        name: "{{ lldp_service }}"
        enabled: yes
        state: started
        
    - name: Verify LLDP service is running
      systemd:
        name: "{{ lldp_service }}"
      register: lldp_status
      
    - name: Display LLDP service status
      debug:
        msg: "LLDP service is {{ lldp_status.status.ActiveState }}"
        
  handlers:
    - name: restart lldpd
      systemd:
        name: "{{ lldp_service }}"
        state: restarted
