---
- name: Deploy and Configure LLDP with Non-Root Access (Compatible)
  hosts: all
  become: yes

  vars:
    lldp_package: lldpd
    lldp_service: lldpd
    lldp_socket_group: lldpd

  tasks:
    - name: Install LLDP daemon on Debian/Ubuntu
      apt:
        name: "{{ lldp_package }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install LLDP daemon on RedHat/CentOS
      yum:
        name: "{{ lldp_package }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Create lldpd group for socket access
      group:
        name: "{{ lldp_socket_group }}"
        state: present
        system: yes

    - name: Add current user to lldpd group
      user:
        name: "{{ ansible_user }}"
        groups: "{{ lldp_socket_group }}"
        append: yes
      when: ansible_user is defined and ansible_user != 'root'

    - name: Clear lldpd config (Debian/Ubuntu) - no -g flag
      copy:
        content: |
          # Managed by Ansible
          # Basic LLDP configuration (version 1.0.x compatible)
          DAEMON_ARGS=""
        dest: /etc/default/lldpd
        mode: '0644'
        backup: yes
      when: ansible_os_family == "Debian"

    - name: Clear lldpd config (RedHat/CentOS) - no -g flag
      copy:
        content: |
          # Managed by Ansible
          # Basic LLDP configuration (version 1.0.x compatible)
          LLDPD_OPTIONS=""
        dest: /etc/sysconfig/lldpd
        mode: '0644'
        backup: yes
      when: ansible_os_family == "RedHat"

    - name: Create systemd override directory
      file:
        path: /etc/systemd/system/lldpd.service.d
        state: directory
        mode: '0755'

    - name: Create systemd override to fix socket permissions
      copy:
        content: |
          # Managed by Ansible
          # Fix socket permissions for non-root access
          [Service]
          ExecStartPost=/bin/sh -c 'sleep 1; chgrp {{ lldp_socket_group }} /run/lldpd.socket; chmod g+rw /run/lldpd.socket'
        dest: /etc/systemd/system/lldpd.service.d/socket-permissions.conf
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Ensure LLDP service is enabled and started
      systemd:
        name: "{{ lldp_service }}"
        enabled: yes
        state: restarted

    - name: Wait for service to stabilize and socket to be created
      wait_for:
        path: /run/lldpd.socket
        timeout: 10

    - name: Ensure socket has correct permissions
      file:
        path: /run/lldpd.socket
        group: "{{ lldp_socket_group }}"
        mode: '0660'

    - name: Verify LLDP service is running
      command: systemctl is-active lldpd
      register: service_status
      changed_when: false
      failed_when: false

    - name: Display service status
      debug:
        msg: "LLDP service status: {{ service_status.stdout }}"

    - name: Test lldpctl access
      command: lldpctl show chassis
      register: lldpctl_test
      become_user: "{{ ansible_user }}"
      become: yes
      changed_when: false
      failed_when: false

    - name: Display lldpctl test result
      debug:
        msg: "{{ 'SUCCESS: Non-root user can run lldpctl' if lldpctl_test.rc == 0 else 'NOTE: User needs to log out/in or run: newgrp ' + lldp_socket_group }}"

    - name: Display instructions
      debug:
        msg:
          - "LLDP daemon is now running!"
          - "Users in the '{{ lldp_socket_group }}' group can run lldpctl without sudo."
          - "If lldpctl doesn't work immediately, users should:"
          - "  1. Log out and log back in, OR"
          - "  2. Run: newgrp {{ lldp_socket_group }}"
