---
- name: Fix lldpcli Access via Sudoers
  hosts: all
  become: yes

  vars:
    lldp_socket_group: lldpd

  tasks:
    - name: Check if lldpcli exists
      stat:
        path: /usr/sbin/lldpcli
      register: lldpcli_check

    - name: Display lldpcli status
      debug:
        msg: "lldpcli found at /usr/sbin/lldpcli"
      when: lldpcli_check.stat.exists

    - name: Ensure lldpd group exists
      group:
        name: "{{ lldp_socket_group }}"
        state: present
        system: yes

    - name: Add current user to lldpd group
      user:
        name: "{{ ansible_user }}"
        groups: "{{ lldp_socket_group }}"
        append: yes
      when: ansible_user is defined and ansible_user != 'root'

    - name: Configure sudoers for lldpcli/lldpctl access
      copy:
        content: |
          # Managed by Ansible
          # Allow users in lldpd group to run lldpcli and lldpctl without password
          # This is more secure and survives package updates
          %{{ lldp_socket_group }} ALL=(ALL) NOPASSWD: /usr/sbin/lldpcli, /usr/sbin/lldpctl, /usr/bin/lldpcli, /usr/bin/lldpctl
        dest: "/etc/sudoers.d/lldp"
        mode: '0440'
        owner: root
        group: root
        validate: 'visudo -cf %s'
      when: lldpcli_check.stat.exists

    - name: Verify sudoers configuration
      command: cat /etc/sudoers.d/lldp
      register: sudoers_content
      changed_when: false

    - name: Display sudoers configuration
      debug:
        msg: "✅ Sudoers configured for lldpd group"

    - name: Test lldpcli execution via sudo
      command: sudo lldpcli show chassis
      become: no
      register: test_exec
      failed_when: false
      changed_when: false
      when: ansible_user != 'root'

    - name: Display test result
      debug:
        msg: "{{ '✅ SUCCESS: Non-root user can now run sudo lldpcli!' if test_exec.rc == 0 else '⚠️  Note: User may need to log out/in or run: newgrp ' + lldp_socket_group }}"
      when: ansible_user != 'root'

    - name: Show usage instructions
      debug:
        msg:
          - "Non-root users can now run LLDP commands using:"
          - "  sudo lldpcli show neighbors"
          - "  sudo lldpcli show chassis"
          - "  sudo lldpctl show neighbors"
          - ""
          - "No password required for users in the '{{ lldp_socket_group }}' group"
          - ""
          - "Benefits of sudoers approach:"
          - "  - More secure (doesn't modify binary permissions)"
          - "  - Survives package updates"
          - "  - Granular control over who can run lldp commands"
      when: ansible_user != 'root'
