---
- name: Setup Passwordless Sudo for Non-Root Users
  hosts: all
  become: yes
  # This playbook must be run with --ask-become-pass if you don't have passwordless sudo yet
  # Usage: ansible-playbook -i inventory.ini setup_passwordless_sudo.yml --ask-become-pass

  tasks:
    - name: Skip setup for root users
      debug:
        msg: "Skipping {{ inventory_hostname }} - already running as root"
      when: ansible_user == 'root'

    - name: Create sudoers.d entry for user (non-root hosts only)
      copy:
        content: |
          # Managed by Ansible
          # Allow {{ ansible_user }} to run all commands without password
          {{ ansible_user }} ALL=(ALL) NOPASSWD: ALL
        dest: "/etc/sudoers.d/{{ ansible_user }}"
        mode: '0440'
        validate: 'visudo -cf %s'
      when: ansible_user != 'root'

    - name: Verify sudoers entry was created
      command: "cat /etc/sudoers.d/{{ ansible_user }}"
      register: sudoers_content
      changed_when: false
      when: ansible_user != 'root'

    - name: Display result
      debug:
        msg: "✅ Passwordless sudo configured for {{ ansible_user }} on {{ inventory_hostname }}"
      when: ansible_user != 'root'

    - name: Test passwordless sudo
      command: sudo -n whoami
      become: no
      register: sudo_verify
      changed_when: false
      when: ansible_user != 'root'

    - name: Display test result
      debug:
        msg: "{{ '✅ SUCCESS: Passwordless sudo is working!' if sudo_verify.rc == 0 else '❌ FAILED: Passwordless sudo still not working' }}"
      when: ansible_user != 'root' and sudo_verify is defined
